name: hm_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0

# Para crear el servidor web y los endpoints API
  shelf: ^1.4.1
  shelf_router: ^1.1.4

  # Para conectarte a MongoDB
  mongo_dart: ^0.10.5

  # Para manejar peticiones HTTP, útil para Cloudinary
  http: ^1.5.0 
  
  # Para hash de contraseñas
  crypto: ^3.0.3
dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
